[package]
name = "leetcode-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
criterion = { version = "0.6.0", features = ["html_reports"] }

[[bench]]
name = "_0125_valid_palindrome"
harness = false